import os

DATABASE = 'urca'
SERVER = 'ls-b82e6d5a49dbc8dc83ff82d1fdc76d7b103ff763.cemcytkjo1qw.us-east-1.rds.amazonaws.com'
USER = 'dbmasteruser'
PASSWORD = '=-k]d<xyGQQZl08C_PSLPw+ZQVl|*.]4'

INPUT_PATH_PRECIPITACAO = os.getcwd() + '/arquivos/precipitacao/'
INPUT_PATH_PRECIPITACAO_GEFS = INPUT_PATH_PRECIPITACAO + 'GEFS/'
INPUT_PATH_PRECIPITACAO_ETA = INPUT_PATH_PRECIPITACAO + 'ETA/'
INPUT_PATH_PRECIPITACAO_ECMWF = INPUT_PATH_PRECIPITACAO + 'ECMWF/'